"""Built-in wording for every editable site text: key -> (default text, admin group).

The database row with the same key (Admin -> Site texts) overrides these. Change the
default here only to change what NEW installs / not-yet-edited texts say.
"""

DEFAULTS = {
    'about.bio': ('Bio', 'About page'),
    'about.download_resume': ('Download resume', 'About page'),
    'about.experience': ('Experience', 'About page'),
    'about.no_bio': ('My story is coming soon.', 'About page'),
    'about.present': ('Present', 'About page'),
    'about.skills': ('Skills', 'About page'),
    'about.title': ('About — {name}', 'About page'),
    'about.where_i_ve_worked': ("Where I've worked", 'About page'),
    'account.account': ('Account', 'Account pages'),
    'account.account_details': ('Account details', 'Account pages'),
    'account.already_have_an_account': ('Already have an account?', 'Account pages'),
    'account.change_password': ('Change password', 'Account pages'),
    'account.confirm_password': ('Confirm password', 'Account pages'),
    'account.create_account': ('Create account', 'Account pages'),
    'account.create_an_account': ('Create an account.', 'Account pages'),
    'account.current_password': ('Current password', 'Account pages'),
    'account.first_name': ('First name', 'Account pages'),
    'account.last_name': ('Last name', 'Account pages'),
    'account.let_me_in': ('Let me in', 'Account pages'),
    'account.liked_articles': ('♡ Liked articles', 'Account pages'),
    'account.log_back_in': ('Log back in →', 'Account pages'),
    'account.log_in': ('Log in.', 'Account pages'),
    'account.log_out': ('Log out', 'Account pages'),
    'account.logged_out': ('Logged out.', 'Account pages'),
    'account.lost_password': ('Lost password', 'Account pages'),
    'account.members_only': ('Members only', 'Account pages'),
    'account.my_account': ('My account.', 'Account pages'),
    'account.my_comments': ('💬 My comments', 'Account pages'),
    'account.new_answer': ('New answer', 'Account pages'),
    'account.new_here': ('New here?', 'Account pages'),
    'account.no_fluff_just_your_inbox': ('Welcome back. Log in to like, save and comment.', 'Account pages'),
    'account.no_likes_yet_hit_on': ('No likes yet — tap ♡ on a post you enjoy.', 'Account pages'),
    'account.nothing_saved_yet_look_for': ('Nothing saved yet — tap 🔖 Save on any post to keep it here.', 'Account pages'),
    'account.question': ('Question', 'Account pages'),
    'account.remove': ('Remove', 'Account pages'),
    'account.save_articles_like_posts_and': ('Save articles, like posts and keep track of your comments.', 'Account pages'),
    'account.save_details': ('Save details', 'Account pages'),
    'account.save_security_question': ('Save security question', 'Account pages'),
    'account.saved_articles': ('🔖 Saved articles', 'Account pages'),
    'account.see_you_soon': ('See you soon', 'Account pages'),
    'account.signed_in_as': ('Signed in as', 'Account pages'),
    'account.title_join': ('Join — {name}', 'Account pages'),
    'account.title_log_in': ('Log in — {name}', 'Account pages'),
    'account.title_logged_out': ('Logged out — {name}', 'Account pages'),
    'account.title_my_account': ('My account — {name}', 'Account pages'),
    'account.update_password': ('Update password', 'Account pages'),
    'account.used_to_recover_your_account': ('Used to recover your account — no email needed.', 'Account pages'),
    'account.you_don_t_have_one': ("You haven't set one yet — add one so you can recover your account if you forget your password.", 'Account pages'),
    'account.you_haven_t_commented_on': ("You haven't commented on anything yet.", 'Account pages'),
    'account.you_ve_been_signed_out': ("You've been signed out.", 'Account pages'),
    'common.email_placeholder': ('you@example.com', 'Account pages'),
    'common.password_repeat_placeholder': ('One more time', 'Account pages'),
    'recover.account_recovery': ('Account recovery', 'Account pages'),
    'recover.answer_exactly_as_you_set': ("Answer exactly as you set it up — it's not case-sensitive.", 'Account pages'),
    'recover.choose_a_new_password': ('Choose a new password.', 'Account pages'),
    'recover.continue': ('Continue', 'Account pages'),
    'recover.forgot_your_password': ('Forgot your password?', 'Account pages'),
    'recover.no_email_needed_just_answer': ('No email needed — just answer your security question.', 'Account pages'),
    'recover.reset_password': ('Reset password', 'Account pages'),
    'recover.start_over': ('Start over', 'Account pages'),
    'recover.step_2_of_3': ('Step 2 of 3', 'Account pages'),
    'recover.step_3_of_3': ('Step 3 of 3', 'Account pages'),
    'recover.title_recover_account': ('Recover account — {name}', 'Account pages'),
    'recover.title_security_question': ('Security question — {name}', 'Account pages'),
    'recover.title_set_a_new_password': ('Set a new password — {name}', 'Account pages'),
    'recover.verified_set_a_new_password': ('Verified — set a new password to finish.', 'Account pages'),
    'recover.verify': ('Verify', 'Account pages'),
    'recover.your_answer': ('Your answer', 'Account pages'),
    'blog_detail.be_the_first_to_comment': ('Be the first to comment.', 'Blog pages'),
    'blog_detail.comment': ('Comment', 'Blog pages'),
    'blog_detail.comments_are_shown_after_approval': ('Comments appear once they have been approved.', 'Blog pages'),
    'blog_detail.comments_heading': ('Comments ({count})', 'Blog pages'),
    'blog_detail.delete': ('Delete', 'Blog pages'),
    'blog_detail.email_never_published': ('Email (never published)', 'Blog pages'),
    'blog_detail.leave_a_comment': ('Leave a comment', 'Blog pages'),
    'blog_detail.like_many': ('Likes', 'Blog pages'),
    'blog_detail.like_one': ('Like', 'Blog pages'),
    'blog_detail.more_in': ('More in {category}', 'Blog pages'),
    'blog_detail.post_comment': ('Post comment', 'Blog pages'),
    'blog_detail.post_reply': ('Post reply', 'Blog pages'),
    'blog_detail.reply': ('Reply', 'Blog pages'),
    'blog_detail.save': ('🔖 Save', 'Blog pages'),
    'blog_detail.save_log_in': ('🔖 Log in to save', 'Blog pages'),
    'blog_detail.saved': ('🔖 Saved', 'Blog pages'),
    'blog_detail.write_a_reply': ('Write a reply…', 'Blog pages'),
    'blog_list.all': ('All', 'Blog pages'),
    'blog_list.filter_posts_by_category': ('Filter posts by category', 'Blog pages'),
    'blog_list.go': ('Search', 'Blog pages'),
    'blog_list.no_posts_found_try_a': ('No posts found — try a different search or category.', 'Blog pages'),
    'blog_list.search_label': ('Search posts', 'Blog pages'),
    'blog_list.search_placeholder': ('Search posts…', 'Blog pages'),
    'blog_list.search_results': ('Search results for “{keyword}” — {count} post{s} found.', 'Blog pages'),
    'blog_list.title': ('Blog — {name}', 'Blog pages'),
    'blog_list.writing_on_things_i_m': ("Notes, ideas and things I'm learning.", 'Blog pages'),
    'contact.contact': ('Contact', 'Contact page'),
    'contact.details': ('Details', 'Contact page'),
    'contact.email_address': ('Email address', 'Contact page'),
    'contact.message': ('Message', 'Contact page'),
    'contact.optional': ('(optional)', 'Contact page'),
    'contact.other_ways_to_reach_me': ('Other ways to reach me', 'Contact page'),
    'contact.send_message': ('Send message', 'Contact page'),
    'contact.subject': ('Subject', 'Contact page'),
    'contact.tell_me_a_bit_about': ("Tell me a bit about what you need — I'll get back to you shortly.", 'Contact page'),
    'contact.title': ('Contact — {name}', 'Contact page'),
    'contact.your_message': ('Your message', 'Contact page'),
    'error400.badge': ('Hmm.', 'Error pages'),
    'error400.button': ('Take me home →', 'Error pages'),
    'error400.heading': ("That request didn't make sense.", 'Error pages'),
    'error400.text': ('Something about the link or form you sent was off. Go back and try again.', 'Error pages'),
    'error400.title': ('400 — Bad request', 'Error pages'),
    'error403.badge': ('Hold up.', 'Error pages'),
    'error403.button': ('Take me home →', 'Error pages'),
    'error403.heading': ("You can't go in there.", 'Error pages'),
    'error403.text': ("You don't have permission to view this page. If you think that's a mistake, log in or get in touch.", 'Error pages'),
    'error403.title': ('403 — No access', 'Error pages'),
    'error404.badge': ('Oops.', 'Error pages'),
    'error404.button': ('Take me home →', 'Error pages'),
    'error404.heading': ('This page ghosted you.', 'Error pages'),
    'error404.text': ("We looked everywhere. Behind the couch. In the junk drawer. It's gone.", 'Error pages'),
    'error404.title': ('404 — Page not found', 'Error pages'),
    'error500.badge': ('Oops.', 'Error pages'),
    'error500.button': ('Take me home →', 'Error pages'),
    'error500.heading': ('Something broke on my end.', 'Error pages'),
    'error500.text': ("It's not you. The error has been logged and I'll look into it. Please try again in a moment.", 'Error pages'),
    'error500.title': ('500 — Server error', 'Error pages'),
    'gallery.a_few_extra_pictures': ('Pictures and moments worth keeping.', 'Gallery page'),
    'gallery.no_images_yet_add_some': ('No images yet — check back soon.', 'Gallery page'),
    'gallery.title': ('Gallery — {name}', 'Gallery page'),
    'layout.contact_form': ('Contact form', 'Header & footer'),
    'layout.elsewhere': ('Elsewhere', 'Header & footer'),
    'layout.explore': ('Explore', 'Header & footer'),
    'layout.log_in': ('Log in', 'Header & footer'),
    'layout.meta_description': ('Personal portfolio & blog', 'Header & footer'),
    'layout.my_account': ('My account', 'Header & footer'),
    'layout.no_social_links_added_yet': ('Social links coming soon.', 'Header & footer'),
    'layout.primary': ('Primary navigation', 'Header & footer'),
    'layout.rights': ('{name}. All rights reserved.', 'Header & footer'),
    'layout.say_hello': ('Say hello', 'Header & footer'),
    'layout.skip_to_main_content': ('Skip to main content', 'Header & footer'),
    'layout.tagline': ('Portfolio & blog', 'Header & footer'),
    'layout.toggle_menu': ('Open menu', 'Header & footer'),
    'home.a_few_favourites_open_any': ('A few favourites — open any project for the full write-up.', 'Home page'),
    'home.about_fallback_heading': ('A bit about me', 'Home page'),
    'home.blog_categories': ('Blog categories', 'Home page'),
    'home.email_me': ('Email me', 'Home page'),
    'home.from_the_blog': ('From the blog', 'Home page'),
    'home.got_a_project_let_s': ("Got a project? Let's talk.", 'Home page'),
    'home.hero_fallback_text': ('Welcome to my portfolio and blog.', 'Home page'),
    'home.hero_fallback_title': ("Hi, I'm a creative", 'Home page'),
    'home.more_about_me': ('More about me', 'Home page'),
    'home.portrait_label': ('Portrait', 'Home page'),
    'home.portrait_note': ('coming soon', 'Home page'),
    'home.recent_projects': ('Recent projects', 'Home page'),
    'home.recent_writing': ('Recent writing', 'Home page'),
    'home.see_the_work': ('See the work', 'Home page'),
    'home.selected_work': ('Selected work', 'Home page'),
    'home.tell_me_what_you_need': ("Tell me what you need and I'll get back to you shortly.", 'Home page'),
    'msg.bookmark_removed': ('Removed from your saved articles.', 'Messages'),
    'msg.bookmark_saved': ('Saved to your profile.', 'Messages'),
    'msg.comment_deleted': ('Your comment was deleted.', 'Messages'),
    'msg.comment_forbidden': ('You can only delete your own comments.', 'Messages'),
    'msg.comment_invalid': ('Please fix the errors in your comment and try again.', 'Messages'),
    'msg.comment_submitted': ("Thanks! Your comment has been submitted and will appear once it's approved.", 'Messages'),
    'msg.contact_invalid': ('Please correct the errors below and try again.', 'Messages'),
    'msg.contact_sent': ("Thanks! Your message has been sent — I'll get back to you soon.", 'Messages'),
    'msg.fix_errors': ('Please fix the errors below and try again.', 'Messages'),
    'msg.password_changed': ('Your password was changed.', 'Messages'),
    'msg.password_reset_done': ('Your password was reset — you can log in now.', 'Messages'),
    'msg.profile_updated': ('Your profile was updated.', 'Messages'),
    'msg.recover_not_found': ("We couldn't find a security question for that email.", 'Messages'),
    'msg.recover_wrong_answer': ("That answer doesn't match — try again.", 'Messages'),
    'msg.security_updated': ('Your security question was updated.', 'Messages'),
    'msg.welcome': ('Welcome, {email}!', 'Messages'),
    'common.about': ('About', 'Shared words'),
    'common.all_posts': ('All posts', 'Shared words'),
    'common.all_projects': ('All projects', 'Shared words'),
    'common.answer': ('Answer', 'Shared words'),
    'common.back_to_login': ('Back to login', 'Shared words'),
    'common.back_to_site': ('Back to site', 'Shared words'),
    'common.blog': ('Blog', 'Shared words'),
    'common.confirm_new_password': ('Confirm new password', 'Shared words'),
    'common.email': ('Email', 'Shared words'),
    'common.gallery': ('Gallery', 'Shared words'),
    'common.get_in_touch': ('Get in touch', 'Shared words'),
    'common.hide_password': ('Hide password', 'Shared words'),
    'common.home': ('Home', 'Shared words'),
    'common.join_instead': ('Join instead', 'Shared words'),
    'common.more': ('More', 'Shared words'),
    'common.name': ('Name', 'Shared words'),
    'common.new_password': ('New password', 'Shared words'),
    'common.pagination': ('Pagination', 'Shared words'),
    'common.password': ('Password', 'Shared words'),
    'common.password_placeholder': ('Top secret', 'Shared words'),
    'common.security_question': ('Security question', 'Shared words'),
    'common.show_password': ('Show password', 'Shared words'),
    'common.work': ('Work', 'Shared words'),
    'site.name': ('Portfolio', 'Site-wide'),
    'work_detail.client': ('Client', 'Work pages'),
    'work_detail.link': ('Link', 'Work pages'),
    'work_detail.related_projects': ('Related projects', 'Work pages'),
    'work_detail.visit': ('Visit', 'Work pages'),
    'work_list.case_studies_and_projects_open': ('Case studies and projects — open any one for the full write-up.', 'Work pages'),
    'work_list.clear_filter': ('clear filter', 'Work pages'),
    'work_list.featured': ('Featured', 'Work pages'),
    'work_list.filtered_by_tag': ('Filtered by tag —', 'Work pages'),
    'work_list.no_projects_yet_add_some': ('No projects yet — check back soon.', 'Work pages'),
    'work_list.projects': ('Projects', 'Work pages'),
    'work_list.title': ('Work — {name}', 'Work pages'),
}
