# Generated by Django 5.1.14 on 2026-10-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_unique_email_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, db_index=True, max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site text',
                'verbose_name_plural': 'Site texts',
                'ordering': ['group', 'key'],
            },
        ),
    ]
